"""The companion mirror and its three-way state.

Generated code lives in a `.jiti/` mirror of your source: one companion module per source
file, holding marker-delimited sections — one per `@jiti` declaration, keyed by qualname.
Each section records the spec it was generated for and a hash of its body, which is how
jiti tells an untouched section from one you've edited by hand.
"""

from __future__ import annotations

import ast
import os
import re
import shutil
import subprocess
import sys
import tempfile
import threading
import types
from collections.abc import Callable
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any

from jiti.core.declaration import Declaration, short_hash
from jiti.core.discovery import walk_py_files

_FILE_HEADER = (
    "# Generated by jiti — real code you can read, edit, and own.\n"
    "# Hand-edited sections are tracked and never silently overwritten.\n"
)
_BEGIN = re.compile(r"^# === jiti:(?P<key>(?!end ).+?) ===$")
_HEADER = re.compile(r"^# (?P<field>[\w-]+): (?P<value>.*)$")


def content_hash(text: str) -> str:
    """Hash a section body so edits can be detected regardless of surrounding blank lines."""
    return short_hash(text.strip())


_AGENT_TEST_DEF = re.compile(r"^def test_(?!scratch_)", re.MULTILINE)
_SCRATCH_TEST_DEF = re.compile(r"\bdef test_scratch_")


def scratch_rename(source: str) -> str:
    """Mark agent-written tests as prunable by prefixing their names with `scratch_`.

    Author-declared jiti-tests keep their real names; only the agent's own exploratory tests
    are scratch, so a later `jiti test prune`/`keep` can drop or promote them by this prefix.
    """
    return _AGENT_TEST_DEF.sub("def test_scratch_", source)


def scratch_promote(source: str) -> str:
    """The inverse of `scratch_rename`: strip `test_scratch_` prefixes back to `test_*`."""
    return _SCRATCH_TEST_DEF.sub("def test_", source)


@dataclass(frozen=True)
class Section:
    """One declaration's generated body plus the provenance recorded in its header."""

    key: str
    spec_hash: str
    gen_hash: str
    body: str

    @property
    def edited(self) -> bool:
        """True if the body on disk differs from what jiti last generated."""
        return content_hash(self.body) != self.gen_hash


class Action(Enum):
    """What resolving a declaration against the store says to do next."""

    GENERATE = "generate"
    """No section exists yet."""

    RUN = "run"
    """Untouched section whose spec still matches — run the cached code."""

    REGENERATE = "regenerate"
    """Untouched section whose spec changed — regenerate it."""

    RUN_OWNED = "run_owned"
    """Hand-edited section whose spec still matches — run the user's code as-is."""

    CONFLICT = "conflict"
    """Hand-edited section whose spec changed — refuse to clobber; surface a conflict."""


@dataclass(frozen=True)
class Resolution:
    action: Action
    section: Section | None


@dataclass(frozen=True)
class JitiStore:
    """Reads and writes the `.jiti/` companion mirror rooted at `root`."""

    root: Path
    # Serializes the read→render→write of a companion file: two declarations in one module
    # generating on different threads would otherwise race the read-modify-write in
    # `_upsert` and silently drop a section. Deliberately a plain Lock, not an RLock — the
    # critical section can never re-enter the store (a cascade commits its own section
    # before its caller reaches `write`), so a deadlock here means that invariant broke
    # and should surface, not be silently permitted.
    _write_lock: threading.Lock = field(
        default_factory=threading.Lock, init=False, repr=False, compare=False
    )

    def impl_path(self, declaration: Declaration) -> Path:
        return self.root / module_relpath(declaration.module)

    def test_path(self, declaration: Declaration) -> Path:
        return test_path_for_module(self.root, declaration.module)

    def read_section(self, declaration: Declaration) -> Section | None:
        try:
            text = self.impl_path(declaration).read_text()
        except FileNotFoundError:
            return None
        return parse_sections(text).get(declaration.key)

    def resolve(self, declaration: Declaration) -> Resolution:
        section = self.read_section(declaration)
        if section is None:
            return Resolution(Action.GENERATE, None)
        spec_matches = section.spec_hash == declaration.spec_hash
        if section.edited:
            return Resolution(Action.RUN_OWNED if spec_matches else Action.CONFLICT, section)
        return Resolution(Action.RUN if spec_matches else Action.REGENERATE, section)

    def write(self, declaration: Declaration, impl_body: str, test_body: str) -> Section:
        """Persist (or replace) the impl and test sections, hoisting imports to the top."""
        spec = declaration.spec_hash
        impl_imports, impl_code = _split_imports(impl_body)
        impl = Section(declaration.key, spec, content_hash(impl_code), impl_code)
        self._upsert(self.impl_path(declaration), impl, impl_imports)
        test_imports, test_code = _split_imports(test_body)
        test = Section(declaration.key, spec, content_hash(test_code), test_code)
        self._upsert(self.test_path(declaration), test, test_imports)
        return impl

    def _upsert(self, path: Path, section: Section, imports: str) -> None:
        # The lock guards ONLY this read→render→write. It must never span generation or
        # validation (both can cascade back into the store) — widening it would deadlock.
        with self._write_lock:
            try:
                existing_imports, sections = parse_file(path.read_text())
            except FileNotFoundError:
                existing_imports, sections = "", {}
            sections[section.key] = section
            combined = "\n".join(part for part in (existing_imports, imports) if part)
            path.parent.mkdir(parents=True, exist_ok=True)
            atomic_write(path, render_file(combined, sections), _clean_imports)

    def load(self, declaration: Declaration) -> Callable[..., Any]:
        """Compile the companion fresh (no bytecode cache) and return the declared function."""
        return self._load(self.impl_path(declaration), declaration)

    def read_test_section(self, declaration: Declaration) -> Section | None:
        try:
            text = self.test_path(declaration).read_text()
        except FileNotFoundError:
            return None
        return parse_sections(text).get(declaration.key)

    def write_test(self, declaration: Declaration, body: str) -> Section:
        """Persist a generated jiti-test body as a section in the test file (no impl section)."""
        imports, code = _split_imports(body)
        section = Section(declaration.key, declaration.spec_hash, content_hash(code), code)
        self._upsert(self.test_path(declaration), section, imports)
        return section

    def load_test(self, declaration: Declaration) -> types.FunctionType:
        """Compile the committed test file and return the generated test function."""
        return self._load(self.test_path(declaration), declaration)

    def _load(self, path: Path, declaration: Declaration) -> types.FunctionType:
        namespace: dict[str, Any] = {
            "__name__": f"_jiti.{declaration.module}",
            "__file__": str(path),
        }
        # `dont_inherit=True` isolates the .jiti file from this module's compile flags —
        # without it, `from __future__ import annotations` at the top of store.py leaks in
        # and stringifies the loaded function's annotations, which breaks downstream
        # introspection (e.g. pydantic's runtime type checks) that expect live class objects.
        exec(compile(path.read_text(), str(path), "exec", dont_inherit=True), namespace)
        # No drift check: the body-only contract splices the stub's def line into the .jiti
        # file verbatim, so the signature can't drift at generation time. A hand-edit to a
        # `.jiti` def line will be caught by pydantic's runtime contract (called against the
        # caller's args, which conform to the stub's signature) with a clear ValidationError.
        return namespace[declaration.name]

    def clear(self) -> None:
        """Delete the entire generated mirror."""
        if self.root.exists():
            shutil.rmtree(self.root)


def drop_section(path: Path, key: str) -> bool:
    """Remove `key` from a companion file, deleting the file if no sections remain.

    Returns True if the file was deleted. A missing file or absent key is a no-op.
    """
    try:
        imports, sections = parse_file(path.read_text())
    except FileNotFoundError:
        return False
    if key not in sections:
        return False
    del sections[key]
    save_sections(path, imports, sections)
    return not sections


def save_sections(path: Path, imports: str, sections: dict[str, Section]) -> None:
    """Persist a companion file's sections, deleting the file if there are none left."""
    if not sections:
        path.unlink(missing_ok=True)
        return
    atomic_write(path, render_file(imports, sections), _clean_imports)


def remove_empty_dirs(root: Path) -> None:
    """Delete empty directories under `root`, and `root` itself if it ends up empty."""
    if not root.exists():
        return
    for path in sorted(root.rglob("*"), reverse=True):
        if path.is_dir() and not any(path.iterdir()):
            path.rmdir()
    if not any(root.iterdir()):
        root.rmdir()


def render_section(section: Section) -> str:
    return "\n".join(
        [
            _begin_marker(section.key),
            f"# spec-hash: {section.spec_hash}",
            f"# gen-hash: {section.gen_hash}",
            "",
            section.body.strip("\n"),
            _end_marker(section.key),
        ]
    )


def render_file(imports: str, sections: dict[str, Section]) -> str:
    body = "\n\n".join(render_section(section) for section in sections.values())
    preamble = f"{_FILE_HEADER}\n{imports}\n" if imports else _FILE_HEADER
    return f"{preamble}\n{body}\n"


def parse_file(text: str) -> tuple[str, dict[str, Section]]:
    """Split a companion into its top import block and its declaration sections."""
    lines = text.splitlines()
    first_marker = next((i for i, line in enumerate(lines) if _BEGIN.match(line)), len(lines))
    imports = "\n".join(
        line for line in lines[:first_marker] if line.strip() and not line.lstrip().startswith("#")
    )
    return imports, parse_sections(text)


def parse_sections(text: str) -> dict[str, Section]:
    lines = text.splitlines()
    sections: dict[str, Section] = {}
    index = 0
    while index < len(lines):
        begin = _BEGIN.match(lines[index])
        if not begin:
            index += 1
            continue
        key = begin.group("key")
        index, section = _parse_one(lines, index + 1, key)
        sections[key] = section
    return sections


def _parse_one(lines: list[str], index: int, key: str) -> tuple[int, Section]:
    fields: dict[str, str] = {}
    while index < len(lines) and (header := _HEADER.match(lines[index])):
        fields[header.group("field")] = header.group("value")
        index += 1
    end_marker = _end_marker(key)
    body_start = index
    while index < len(lines) and lines[index] != end_marker:
        index += 1
    body = "\n".join(lines[body_start:index]).strip("\n")
    section = Section(
        key=key,
        spec_hash=fields.get("spec-hash", ""),
        gen_hash=fields.get("gen-hash", ""),
        body=body,
    )
    return index + 1, section


def _split_imports(source: str) -> tuple[str, str]:
    """Separate top-level import statements from the rest of a translation unit.

    `from __future__` imports are dropped entirely. The user's source can use them
    (stringifying its own stub annotations is fine — we splice the stub's def line as
    text anyway), but a `__future__` directive in the `.jiti` file would stringify the
    loaded function's annotations, which downstream introspection (pydantic's runtime
    contract, signature inspection) needs as live class objects.
    """
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return "", source
    lines = source.splitlines()
    import_lines: set[int] = set()
    imports: list[str] = []
    for node in tree.body:
        if isinstance(node, ast.Import | ast.ImportFrom):
            end = node.end_lineno or node.lineno
            import_lines.update(range(node.lineno, end + 1))
            if isinstance(node, ast.ImportFrom) and node.module == "__future__":
                continue
            imports.append("\n".join(lines[node.lineno - 1 : end]))
    body = "\n".join(line for number, line in enumerate(lines, 1) if number not in import_lines)
    body = re.sub(r"\n{3,}", "\n\n", body).strip("\n")  # close the gap where imports were
    return "\n".join(imports), body


def atomic_write(path: Path, text: str, post_process: Callable[[Path], None] | None = None) -> None:
    """Publish `text` to `path` via a same-dir temp + atomic rename so readers never see a
    half-written file. The temp file ends in `.py` so post-processors (e.g. ruff) treat it
    as Python; it lives beside the target so the rename stays on one filesystem.
    """
    fd, name = tempfile.mkstemp(dir=path.parent, prefix=f"{path.stem}.", suffix=".py")
    os.close(fd)
    tmp = Path(name)
    try:
        tmp.write_text(text)
        if post_process is not None:
            post_process(tmp)
        os.replace(tmp, path)
    except BaseException:
        tmp.unlink(missing_ok=True)
        raise


def _clean_imports(path: Path) -> None:
    """Dedupe, merge, sort, and prune the hoisted import block (bodies untouched) via ruff.

    Invoked through the interpreter so it works without the venv's bin on PATH; a missing
    ruff degrades to un-deduped imports rather than crashing an already-finished generation.
    """
    subprocess.run(
        [
            sys.executable,
            "-m",
            "ruff",
            "check",
            "--fix",
            "--select",
            "F401,I",
            "--quiet",
            str(path),
        ],
        capture_output=True,
    )


def _begin_marker(key: str) -> str:
    return f"# === jiti:{key} ==="


def _end_marker(key: str) -> str:
    return f"# === jiti:end {key} ==="


def module_relpath(module: str) -> Path:
    """The companion-relative path for a dotted module: `app.text` → `app/text.py`."""
    return Path(*module.split(".")).with_suffix(".py")


def test_path_for_module(mirror: Path, module: str) -> Path:
    """Companion test path for a dotted module: `app.text` → `<mirror>/tests/app/test_text.py`."""
    relpath = module_relpath(module)
    return mirror / "tests" / relpath.with_name(f"test_{relpath.name}")


@dataclass(frozen=True)
class SectionRef:
    """A generated impl section located in the mirror, tied back to its source module."""

    module: str
    qualname: str
    section: Section
    impl_path: Path

    @property
    def key(self) -> str:
        return f"{self.module}.{self.qualname}"

    @property
    def name(self) -> str:
        """The defined symbol — the bare function name, or the method name for `Class.method`."""
        return self.qualname.rsplit(".", 1)[-1]

    @property
    def is_method(self) -> bool:
        return "." in self.qualname


def inventory(root: Path) -> list[SectionRef]:
    """Every generated impl section in the mirror (the `tests/` subtree is excluded)."""
    root = root.resolve()
    tests_dir = root / "tests"
    refs: list[SectionRef] = []
    for path in sorted(walk_py_files(root)):
        if path.is_relative_to(tests_dir):
            continue
        module = ".".join(path.relative_to(root).with_suffix("").parts)
        for key, section in parse_sections(path.read_text()).items():
            qualname = key.removeprefix(f"{module}.")
            refs.append(SectionRef(module, qualname, section, path))
    return refs
