"""The `@jiti` decorator and its descriptor-safe wrapper.

The wrapper introspects the stub lazily on first call (so generated code can import back into
a fully-loaded module without cycles), then dispatches to the engine, which generates if
needed and returns the real implementation. It implements the descriptor protocol so methods
bind: `instance.method(...)` runs with the instance as the first argument.
"""

from __future__ import annotations

import functools
import types
from collections.abc import Callable
from typing import Any, cast, overload

from jiti.agent.engine import Engine, default_engine
from jiti.core.declaration import Declaration, Gate, analyze_body, gate_for, introspect
from jiti.core.errors import JitiError
from jiti.core.validate import CONTRACT


class _JitiCallable:
    """Lazily resolves a stub to its generated implementation and dispatches to it."""

    def __init__(self, func: Callable[..., Any], engine: Engine | None) -> None:
        if not isinstance(func, types.FunctionType):
            raise JitiError("@jiti can only decorate plain functions and methods.")
        analyze_body(func)  # fail fast at decoration time if the body is a real implementation
        self._func: types.FunctionType = func
        self._engine = engine
        self._owner: type | None = None
        self._impl: Callable[..., Any] | None = None
        self._gates: list[Gate] = []
        functools.update_wrapper(self, func)

    def __set_name__(self, owner: type, name: str) -> None:
        self._owner = owner

    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        return self._resolve(args, kwargs)(*args, **kwargs)

    def __get__(self, instance: object, owner: type | None = None) -> Callable[..., Any]:
        # Class access (`Cls.method`) returns the wrapper unresolved — resolving here would
        # recurse, since introspecting the class to build its context reads its attributes.
        if instance is None:
            return self

        def bound(*args: Any, **kwargs: Any) -> Any:
            return self._resolve((instance, *args), kwargs)(instance, *args, **kwargs)

        return bound

    def declaration(self) -> Declaration:
        """The canonical spec for this stub — engine and CLI build state from it."""
        return introspect(self._func, self._owner, tuple(self._gates))

    def _resolve(self, args: tuple[object, ...], kwargs: dict[str, object]) -> Callable[..., Any]:
        if self._impl is None:
            engine = self._engine or default_engine()
            engine.discover()  # import test modules so `required_for` gates are registered first
            self._impl = CONTRACT(engine.implement(self.declaration(), args, kwargs))
        return self._impl


class _Jiti:
    """The `@jiti` decorator as a callable object, so it can also host `jiti.required_for`."""

    @overload
    def __call__[F: Callable[..., Any]](self, func: F) -> F: ...

    @overload
    def __call__[F: Callable[..., Any]](
        self, *, engine: Engine | None = ...
    ) -> Callable[[F], F]: ...

    def __call__[F: Callable[..., Any]](
        self, func: F | None = None, *, engine: Engine | None = None
    ) -> F | Callable[[F], F]:
        """Declare a function or method by its interface; jiti generates the implementation.

        Use bare (`@jiti`) for the default shared engine, or `@jiti(engine=...)` to supply your
        own (e.g. a custom Anthropic client or store).
        """
        if func is None:
            return lambda target: cast(F, _JitiCallable(target, engine))
        return cast(F, _JitiCallable(func, engine))

    def required_for[F: Callable[..., Any]](self, target: Callable[..., Any]) -> Callable[[F], F]:
        """Register a test as part of `target`'s definition of done — generation must satisfy it.

        Write it in your test file, importing the target. A real-bodied test is run as-is against
        the candidate; an empty-bodied stub is generated by jiti from `target`'s interface.
        """
        if not isinstance(target, _JitiCallable):
            raise JitiError("jiti.required_for(target) needs a @jiti-decorated function or method.")

        def register(test: F) -> F:
            if not isinstance(test, types.FunctionType):
                raise JitiError("jiti.required_for can only decorate a plain test function.")
            gate = gate_for(test, target)
            if not any(existing.name == gate.name for existing in target._gates):
                target._gates.append(gate)  # idempotent: discovery may import a test file twice
            if gate.kind == "human":
                return test
            return cast(F, _jiti_test_runner(test, target))

        return register


def _jiti_test_runner(stub: types.FunctionType, target: _JitiCallable) -> Callable[..., Any]:
    """Wrap a jiti-test stub so running it (e.g. under pytest) generates and runs the real test."""

    @functools.wraps(stub)
    def run(*args: Any, **kwargs: Any) -> Any:
        engine = target._engine or default_engine()
        return engine.run_test(introspect(stub), target.declaration())()

    return run


jiti = _Jiti()
