"""The companion mirror and its three-way state.

Generated code lives in a `.jiti/` mirror of your source: one companion module per source
file, holding marker-delimited sections — one per `@jiti` declaration, keyed by qualname.
Each section records the spec it was generated for and a hash of its body, which is how
jiti tells an untouched section from one you've edited by hand.
"""

from __future__ import annotations

import ast
import os
import re
import shutil
import subprocess
import sys
import tempfile
from collections.abc import Callable
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any

from jiti.declaration import Declaration, short_hash

_FILE_HEADER = (
    "# Generated by jiti — real code you can read, edit, and own.\n"
    "# Hand-edited sections are tracked and never silently overwritten.\n"
)
_BEGIN = re.compile(r"^# === jiti:(?P<key>(?!end ).+?) ===$")
_HEADER = re.compile(r"^# (?P<field>[\w-]+): (?P<value>.*)$")


def content_hash(text: str) -> str:
    """Hash a section body so edits can be detected regardless of surrounding blank lines."""
    return short_hash(text.strip())


@dataclass(frozen=True)
class Section:
    """One declaration's generated body plus the provenance recorded in its header."""

    key: str
    spec_hash: str
    gen_hash: str
    body: str

    @property
    def edited(self) -> bool:
        """True if the body on disk differs from what jiti last generated."""
        return content_hash(self.body) != self.gen_hash


class Action(Enum):
    """What resolving a declaration against the store says to do next."""

    GENERATE = "generate"
    """No section exists yet."""

    RUN = "run"
    """Untouched section whose spec still matches — run the cached code."""

    REGENERATE = "regenerate"
    """Untouched section whose spec changed — regenerate it."""

    RUN_OWNED = "run_owned"
    """Hand-edited section whose spec still matches — run the user's code as-is."""

    CONFLICT = "conflict"
    """Hand-edited section whose spec changed — refuse to clobber; surface a conflict."""


@dataclass(frozen=True)
class Resolution:
    action: Action
    section: Section | None


@dataclass(frozen=True)
class JitiStore:
    """Reads and writes the `.jiti/` companion mirror rooted at `root`."""

    root: Path

    def impl_path(self, declaration: Declaration) -> Path:
        return self.root / _module_relpath(declaration.module)

    def test_path(self, declaration: Declaration) -> Path:
        relpath = _module_relpath(declaration.module)
        return self.root / "tests" / relpath.with_name(f"test_{relpath.name}")

    def read_section(self, declaration: Declaration) -> Section | None:
        try:
            text = self.impl_path(declaration).read_text()
        except FileNotFoundError:
            return None
        return parse_sections(text).get(declaration.key)

    def resolve(self, declaration: Declaration) -> Resolution:
        section = self.read_section(declaration)
        if section is None:
            return Resolution(Action.GENERATE, None)
        spec_matches = section.spec_hash == declaration.spec_hash
        if section.edited:
            return Resolution(Action.RUN_OWNED if spec_matches else Action.CONFLICT, section)
        return Resolution(Action.RUN if spec_matches else Action.REGENERATE, section)

    def write(self, declaration: Declaration, impl_body: str, test_body: str) -> Section:
        """Persist (or replace) the impl and test sections, hoisting imports to the top."""
        spec = declaration.spec_hash
        impl_imports, impl_code = _split_imports(impl_body)
        impl = Section(declaration.key, spec, content_hash(impl_code), impl_code)
        self._upsert(self.impl_path(declaration), impl, impl_imports)
        test_imports, test_code = _split_imports(test_body)
        test = Section(declaration.key, spec, content_hash(test_code), test_code)
        self._upsert(self.test_path(declaration), test, test_imports)
        return impl

    def _upsert(self, path: Path, section: Section, imports: str) -> None:
        try:
            existing_imports, sections = parse_file(path.read_text())
        except FileNotFoundError:
            existing_imports, sections = "", {}
        sections[section.key] = section
        combined = "\n".join(part for part in (existing_imports, imports) if part)
        path.parent.mkdir(parents=True, exist_ok=True)
        _atomic_write(path, render_file(combined, sections))

    def load(self, declaration: Declaration) -> Callable[..., Any]:
        """Compile the companion fresh (no bytecode cache) and return the declared function."""
        path = self.impl_path(declaration)
        namespace: dict[str, Any] = {
            "__name__": f"_jiti.{declaration.module}",
            "__file__": str(path),
        }
        exec(compile(path.read_text(), str(path), "exec"), namespace)
        return namespace[declaration.name]

    def clear(self) -> None:
        """Delete the entire generated mirror."""
        if self.root.exists():
            shutil.rmtree(self.root)


def render_section(section: Section) -> str:
    return "\n".join(
        [
            _begin_marker(section.key),
            f"# spec-hash: {section.spec_hash}",
            f"# gen-hash: {section.gen_hash}",
            "",
            section.body.strip("\n"),
            _end_marker(section.key),
        ]
    )


def render_file(imports: str, sections: dict[str, Section]) -> str:
    body = "\n\n".join(render_section(section) for section in sections.values())
    preamble = f"{_FILE_HEADER}\n{imports}\n" if imports else _FILE_HEADER
    return f"{preamble}\n{body}\n"


def parse_file(text: str) -> tuple[str, dict[str, Section]]:
    """Split a companion into its top import block and its declaration sections."""
    lines = text.splitlines()
    first_marker = next((i for i, line in enumerate(lines) if _BEGIN.match(line)), len(lines))
    imports = "\n".join(
        line for line in lines[:first_marker] if line.strip() and not line.lstrip().startswith("#")
    )
    return imports, parse_sections(text)


def parse_sections(text: str) -> dict[str, Section]:
    lines = text.splitlines()
    sections: dict[str, Section] = {}
    index = 0
    while index < len(lines):
        begin = _BEGIN.match(lines[index])
        if not begin:
            index += 1
            continue
        key = begin.group("key")
        index, section = _parse_one(lines, index + 1, key)
        sections[key] = section
    return sections


def _parse_one(lines: list[str], index: int, key: str) -> tuple[int, Section]:
    fields: dict[str, str] = {}
    while index < len(lines) and (header := _HEADER.match(lines[index])):
        fields[header.group("field")] = header.group("value")
        index += 1
    end_marker = _end_marker(key)
    body_start = index
    while index < len(lines) and lines[index] != end_marker:
        index += 1
    body = "\n".join(lines[body_start:index]).strip("\n")
    section = Section(
        key=key,
        spec_hash=fields.get("spec-hash", ""),
        gen_hash=fields.get("gen-hash", ""),
        body=body,
    )
    return index + 1, section


def _split_imports(source: str) -> tuple[str, str]:
    """Separate top-level import statements from the rest of a translation unit."""
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return "", source
    lines = source.splitlines()
    import_lines: set[int] = set()
    imports: list[str] = []
    for node in tree.body:
        if isinstance(node, ast.Import | ast.ImportFrom):
            end = node.end_lineno or node.lineno
            imports.append("\n".join(lines[node.lineno - 1 : end]))
            import_lines.update(range(node.lineno, end + 1))
    body = "\n".join(line for number, line in enumerate(lines, 1) if number not in import_lines)
    body = re.sub(r"\n{3,}", "\n\n", body).strip("\n")  # close the gap where imports were
    return "\n".join(imports), body


def _atomic_write(path: Path, text: str) -> None:
    """Publish `text` to `path` via a same-directory temp file and an atomic rename, so a
    reader (or a second process cold-starting the same module) never sees a half-written
    companion. This rename is the only concurrency guard jiti makes — see the README's
    "Concurrency" section for why we stop here rather than take on cross-process locks.

    The temp file ends in `.py` (so `_clean_imports`' ruff pass actually processes it) and
    lives beside the target (so the rename stays on one filesystem, where it is atomic).
    """
    fd, name = tempfile.mkstemp(dir=path.parent, prefix=f"{path.stem}.", suffix=".py")
    os.close(fd)
    tmp = Path(name)
    try:
        tmp.write_text(text)
        _clean_imports(tmp)
        os.replace(tmp, path)
    except BaseException:
        tmp.unlink(missing_ok=True)
        raise


def _clean_imports(path: Path) -> None:
    """Dedupe, merge, sort, and prune the hoisted import block (bodies untouched) via ruff.

    Invoked through the interpreter so it works without the venv's bin on PATH; a missing
    ruff degrades to un-deduped imports rather than crashing an already-finished generation.
    """
    subprocess.run(
        [
            sys.executable,
            "-m",
            "ruff",
            "check",
            "--fix",
            "--select",
            "F401,I",
            "--quiet",
            str(path),
        ],
        capture_output=True,
    )


def _begin_marker(key: str) -> str:
    return f"# === jiti:{key} ==="


def _end_marker(key: str) -> str:
    return f"# === jiti:end {key} ==="


def _module_relpath(module: str) -> Path:
    return Path(*module.split(".")).with_suffix(".py")
