"""The companion mirror and its three-way state.

Generated code lives in a `.jiti/` mirror of your source: one companion module per source
file, holding marker-delimited sections — one per `@jiti` declaration, keyed by qualname.
Each section records the spec it was generated for and a hash of its body, which is how
jiti tells an untouched section from one you've edited by hand.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass
from enum import Enum
from pathlib import Path

from jiti.declaration import Declaration

_FILE_HEADER = (
    "# Generated by jiti — real code you can read, edit, and own.\n"
    "# Hand-edited sections are tracked and never silently overwritten.\n"
)
_BEGIN = re.compile(r"^# === jiti:(?P<key>(?!end ).+?) ===$")
_HEADER = re.compile(r"^# (?P<field>[\w-]+): (?P<value>.*)$")


def content_hash(text: str) -> str:
    """Hash a section body so edits can be detected regardless of surrounding blank lines."""
    return hashlib.sha256(text.strip().encode()).hexdigest()[:16]


@dataclass(frozen=True)
class Section:
    """One declaration's generated body plus the provenance recorded in its header."""

    key: str
    spec_hash: str
    gen_hash: str
    tests_hash: str
    body: str

    @property
    def edited(self) -> bool:
        """True if the body on disk differs from what jiti last generated."""
        return content_hash(self.body) != self.gen_hash


class Action(Enum):
    """What resolving a declaration against the store says to do next."""

    GENERATE = "generate"
    """No section exists yet."""

    RUN = "run"
    """Untouched section whose spec still matches — run the cached code."""

    REGENERATE = "regenerate"
    """Untouched section whose spec changed — regenerate it."""

    RUN_OWNED = "run_owned"
    """Hand-edited section whose spec still matches — run the user's code as-is."""

    CONFLICT = "conflict"
    """Hand-edited section whose spec changed — refuse to clobber; surface a conflict."""


@dataclass(frozen=True)
class Resolution:
    action: Action
    section: Section | None


@dataclass(frozen=True)
class JitiStore:
    """Reads and writes the `.jiti/` companion mirror rooted at `root`."""

    root: Path

    def impl_path(self, declaration: Declaration) -> Path:
        return self.root / _module_relpath(declaration.module)

    def test_path(self, declaration: Declaration) -> Path:
        parts = declaration.module.split(".")
        parts[-1] = f"test_{parts[-1]}"
        return self.root / "tests" / Path(*parts).with_suffix(".py")

    def read_section(self, declaration: Declaration) -> Section | None:
        path = self.impl_path(declaration)
        if not path.exists():
            return None
        return parse_sections(path.read_text()).get(declaration.key)

    def resolve(self, declaration: Declaration) -> Resolution:
        section = self.read_section(declaration)
        if section is None:
            return Resolution(Action.GENERATE, None)
        spec_matches = section.spec_hash == declaration.spec_hash
        if section.edited:
            return Resolution(Action.RUN_OWNED if spec_matches else Action.CONFLICT, section)
        return Resolution(Action.RUN if spec_matches else Action.REGENERATE, section)

    def write(self, declaration: Declaration, impl_body: str, test_body: str) -> Section:
        """Persist (or replace) the impl and test sections for a declaration."""
        spec = declaration.spec_hash
        tests_hash = content_hash(test_body)
        impl = Section(declaration.key, spec, content_hash(impl_body), tests_hash, impl_body)
        self._upsert(self.impl_path(declaration), impl)
        self._upsert(
            self.test_path(declaration),
            Section(declaration.key, spec, tests_hash, tests_hash, test_body),
        )
        return impl

    def _upsert(self, path: Path, section: Section) -> None:
        sections = parse_sections(path.read_text()) if path.exists() else {}
        sections[section.key] = section
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render_file(sections))


def render_section(section: Section) -> str:
    return "\n".join(
        [
            f"# === jiti:{section.key} ===",
            f"# spec-hash: {section.spec_hash}",
            f"# gen-hash: {section.gen_hash}",
            f"# tests-hash: {section.tests_hash}",
            "",
            section.body.strip("\n"),
            f"# === jiti:end {section.key} ===",
        ]
    )


def render_file(sections: dict[str, Section]) -> str:
    body = "\n\n".join(render_section(section) for section in sections.values())
    return f"{_FILE_HEADER}\n{body}\n"


def parse_sections(text: str) -> dict[str, Section]:
    lines = text.splitlines()
    sections: dict[str, Section] = {}
    index = 0
    while index < len(lines):
        begin = _BEGIN.match(lines[index])
        if not begin:
            index += 1
            continue
        key = begin.group("key")
        index, section = _parse_one(lines, index + 1, key)
        sections[key] = section
    return sections


def _parse_one(lines: list[str], index: int, key: str) -> tuple[int, Section]:
    fields: dict[str, str] = {}
    while index < len(lines) and (header := _HEADER.match(lines[index])):
        fields[header.group("field")] = header.group("value")
        index += 1
    end_marker = f"# === jiti:end {key} ==="
    body_start = index
    while index < len(lines) and lines[index] != end_marker:
        index += 1
    body = "\n".join(lines[body_start:index]).strip("\n")
    section = Section(
        key=key,
        spec_hash=fields.get("spec-hash", ""),
        gen_hash=fields.get("gen-hash", ""),
        tests_hash=fields.get("tests-hash", ""),
        body=body,
    )
    return index + 1, section


def _module_relpath(module: str) -> Path:
    return Path(*module.split(".")).with_suffix(".py")
